name: Code Changes

on:
  workflow_run:
    workflows: ["Repo Sync"]
    types:
      - completed
  workflow_dispatch:

jobs:
  code-changes:
    runs-on: ubuntu-latest
    env:
      TargetRepo: repo-sync
    steps:
      - name: Checkout ${{ env.TargetRepo }} branch
        uses: actions/checkout@v2
        with:
          ref: ${{ env.TargetRepo }}
      - name: Disable Docker-in-Docker check
        run: |
          sed -i -e "/ServiceController\[\] scServices = ServiceController.GetServices();/,+4 s/^/\/\//" src/Runner.Worker/ContainerOperationProvider.cs && 
          sed -i -e "/var initProcessCgroup = File.ReadLines(\"\/proc\/1\/cgroup\");/,+4 s/^/\/\//" src/Runner.Worker/ContainerOperationProvider.cs
      - name: Fix project git command path
        run: |
          sed -i 's/git update-index --assume-unchanged .\/Runner.Sdk\/BuildConstants.cs/&\//' src/dir.proj
      - name: Commit changes to ${{ env.TargetRepo }}
        uses: EndBug/add-and-commit@v9
        with:
          message: "[Automated] Code changes"
          add: '["src/Runner.Worker/ContainerOperationProvider.cs", "src/dir.proj"]'
