name: Code Changes

on:
  pull_request:
    types:
      - labeled
    branches:
      - tivo-build

jobs:
  code-changes:
    if: contains(github.event.pull_request.labels.*.name, 'repo-sync-automated')
    runs-on: ubuntu-latest
    env:
      TargetRepo: repo-sync
    steps:
      - name: Checkout ${{ env.TargetRepo }} branch
        uses: actions/checkout@v2
        with:
          ref: ${{ env.TargetRepo }}
      - name: Disable Docker-in-Docker check
        run: |
          if [[ ! $(egrep "^\/\/\s+ServiceController\[\] scServices = ServiceController.GetServices\(\);" src/Runner.Worker/ContainerOperationProvider.cs) ]]; then
            sed -i -e "/ServiceController\[\] scServices = ServiceController.GetServices();/,+4 s/^/\/\//" src/Runner.Worker/ContainerOperationProvider.cs
          fi && 
          if [[ ! $(egrep "^\/\/\s+var initProcessCgroup = File.ReadLines\(\"\/proc\/1\/cgroup\"\);" src/Runner.Worker/ContainerOperationProvider.cs) ]]; then 
            sed -i -e "/var initProcessCgroup = File.ReadLines(\"\/proc\/1\/cgroup\");/,+4 s/^/\/\//" src/Runner.Worker/ContainerOperationProvider.cs; 
          fi
      - name: Fix project git command path
        run: |
          if [[ ! $(grep "git update-index --assume-unchanged ./Runner.Sdk/BuildConstants.cs/" src/dir.proj) ]]; then
            sed -i 's/git update-index --assume-unchanged .\/Runner.Sdk\/BuildConstants.cs/&\//' src/dir.proj;
          fi
      - name: Apply runner version to "./releaseVersion"
        run: |
          cp -f ./src/runnerversion ./releaseVersion
      - name: Commit changes to ${{ env.TargetRepo }}
        uses: EndBug/add-and-commit@v9
        with:
          message: "[Automated] apply runner version && rm Docker-in-Docker check"
          add: '["src/Runner.Worker/ContainerOperationProvider.cs", "src/dir.proj", "./releaseVersion"]'
