name: Repo Sync

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

env:
  PR_DESTINATION_BRANCH: 'tivo-build'

jobs:
  get-runner-versions:
    name: Compare tivo/actions-runner and actions/runner release versions
    runs-on: ubuntu-latest
    outputs:
      runner_version_mismatch: ${{ steps.compare_runner_versions.outputs.runner_version_mismatch }}
      runner_version_upstream: ${{ steps.get_upstream_ver.outputs.runner_version }}
      runner_version_tivo: ${{ steps.get_tivo_ver.outputs.runner_version }}
    steps:
      - name: Get version number of latest actions/runner release
        id: get_upstream_ver
        run: |
          UPSTREAM_VER=$(curl -sL https://api.github.com/repos/actions/runner/releases/latest | jq -r .tag_name | cut -c2-)
          echo "GH_RUNNER_VERSION_UPSTREAM=$UPSTREAM_VER" >> $GITHUB_ENV
          echo "runner_version=$UPSTREAM_VER" >> $GITHUB_OUTPUT

      - name: Get version number of latest tivo/actions-runner release
        id: get_tivo_ver
        run: |
          TIVO_VER=$(curl -sL https://api.github.com/repos/tivo/actions-runner/releases/latest | jq -r .tag_name | cut -c2-)
          echo "GH_RUNNER_VERSION_TIVO=$TIVO_VER" >> $GITHUB_ENV
          echo "runner_version=$TIVO_VER" >> $GITHUB_OUTPUT
      
      - name: Compare release versions
        id: compare_runner_versions
        run: |
          [[ "${{ env.GH_RUNNER_VERSION_UPSTREAM }}" != "${{ env.GH_RUNNER_VERSION_TIVO }}" ]] \
          && echo "runner_version_mismatch=true" >> $GITHUB_OUTPUT \
          || echo "runner_version_mismatch=false" >> $GITHUB_OUTPUT

  repo-sync:
    name: "Sync upstream changes to tivo-build branch"
    if: needs.get-runner-versions.outputs.runner_version_mismatch == 'true'
    needs: get-runner-versions
    runs-on: ubuntu-latest
    env:
      GH_RUNNER_VERSION_MISMATCH: ${{ needs.get-runner-versions.outputs.runner_version_mismatch }}
      GH_RUNNER_VERSION_UPSTREAM: ${{ needs.get-runner-versions.outputs.runner_version_upstream }}
      GH_RUNNER_VERSION_TIVO: ${{ needs.get-runner-versions.outputs.runner_version_tivo }}
    steps:
      - run: echo "bruh"
      - name: Perform checkout
        uses: actions/checkout@v3
      - name: Sync repo to branch
        uses: repo-sync/github-sync@v2
        with:
          source_repo: ${{ secrets.REPO_SYNC_SOURCE_REPO }}
          source_branch: v${{ env.GH_RUNNER_VERSION_UPSTREAM }}
          destination_branch: ${{ secrets.REPO_SYNC_INTERMEDIATE_BRANCH }}
          github_token: ${{ secrets.TIVOBOT_GITHUB_ACTION_TOKEN }}
      # - uses: repo-sync/pull-request@v2
      # use fix-diff version because of HTTP 422 errors
      # https://github.com/repo-sync/pull-request/issues/119
      - name: Create pull request
        uses: repo-sync/pull-request@fix-diff
        with:
          source_branch: ${{ secrets.REPO_SYNC_INTERMEDIATE_BRANCH }}
          destination_branch: ${{ env.PR_DESTINATION_BRANCH }}
          pr_title: "[Automated] ${{ github.ref }} into ${{ env.PR_DESTINATION_BRANCH }}"
          pr_label: "repo-sync-automated"
          pr_allow_empty: true
          github_token: ${{ secrets.TIVOBOT_GITHUB_ACTION_TOKEN }}

  code-changes:
    name: "Code changes"
    if: needs.get-runner-versions.outputs.runner_version_mismatch == 'true'
    needs: [get-runner-versions, repo-sync]
    runs-on: ubuntu-latest
    env:
      TargetBranch: repo-sync
    steps:
      - name: Perform checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ env.TargetBranch }}
      - name: Perform code changes
        # The following code changes will disable the docker-in-docker checks found in ./src/Runner.Worker/ContainerOperationProvider.cs 
        # and fixes a git command path issue in ./src/dir.proj
        run: |
          if [[ ! $(egrep "^\/\/\s+ServiceController\[\] scServices = ServiceController.GetServices\(\);" src/Runner.Worker/ContainerOperationProvider.cs) ]]; then
            sed -i -e "/ServiceController\[\] scServices = ServiceController.GetServices();/,+4 s/^/\/\//" src/Runner.Worker/ContainerOperationProvider.cs
          fi && 
          if [[ ! $(egrep "^\/\/\s+var initProcessCgroup = File.ReadLines\(\"\/proc\/1\/cgroup\"\);" src/Runner.Worker/ContainerOperationProvider.cs) ]]; then 
            sed -i -e "/var initProcessCgroup = File.ReadLines(\"\/proc\/1\/cgroup\");/,+4 s/^/\/\//" src/Runner.Worker/ContainerOperationProvider.cs; 
          fi
          if [[ ! $(grep "git update-index --assume-unchanged ./Runner.Sdk/BuildConstants.cs/" src/dir.proj) ]]; then
            sed -i 's/git update-index --assume-unchanged .\/Runner.Sdk\/BuildConstants.cs/&\//' src/dir.proj;
          fi
      - name: Commit changes to ${{ env.TargetBranch }}
        uses: EndBug/add-and-commit@v9
        with:
          message: "[Automated] rm Docker-in-Docker check and fix git cmd build issue"
          add: '["src/Runner.Worker/ContainerOperationProvider.cs", "src/dir.proj"]'
